### ISSUE TITLE
Textarea line wrap

### ISSUE THREAD

**Issue by Dimas-sc** [bueltge/MantisBT-Colorized#10]
Hi,

With this plugin when the user enter a new issue the texteareas don't wrap the line and creates an overflow. Is it possible to put all the text inside the width of the textarea without hidding it?

Example: https://i.imgur.com/rmQM30q.png

Thx

**Comment by bueltge** [comment]
Which browser, I think the problem was solved longer time before?

**Comment by Dimas-sc** [comment]
Firefox 44 and Firefox 46, the MantisVersion1.3.x branch downloaded this morning with Mantis 1.3 RC1

**Comment by Dimas-sc** [comment]
In buttons.css line 99 there is a textarea rule saying "white-space: pre"
In buttons.css line 70 there is a textarea rule saying "white-space: nowrap"

I added this rule in the bottom of colorized.css and it works, but it's not an elegant way to do it:
textarea {
	white-space: normal !important;
}

**Comment by bueltge** [comment]
I have changed the definition of the textarea, please can you test the new version, download her: https://github.com/bueltge/MantisBT-Colorized/archive/MantisVersion1.3.x.zip

Thanks for your feedback.

**Comment by Dimas-sc** [comment]
It works, thx!!

**Comment by bueltge** [comment]
Thanks for your fast feedback! :+1:
