### ISSUE TITLE
Big buttons

### ISSUE THREAD

**Issue by Dimas-sc** [bueltge/MantisBT-Colorized#11]
I'm using the last 1.3.x Colorized release (2016-03-16) and the last 1.3 RC of Mantis BT, and some buttons appears extra large. Is it a bug or a problem of mine?

Screenshot: http://i.imgur.com/NCwqjbY.png

Thx

**Comment by cmmata** [comment]
I have the same problem, with a spanish interface. I just upgraded and didn't noticed it.

**Comment by bueltge** [comment]
Maybe it is a bug.
It is a problem from the default.css, the font site for small buttons is 1em ;)
I will fixed this and you can check it.

**Comment by bueltge** [comment]
Now, please download and test again. It is sufficient if you change the `default.css` in the root of the theme.

**Comment by cmmata** [comment]
I tested it, and it's ok now :+1: Thank you!

**Comment by bueltge** [comment]
Thanks for your tests, feedback.
The last version is now released  - https://github.com/bueltge/MantisBT-Colorized/releases/tag/2016-03-23
