### ISSUE TITLE
Text on password forgotten page floats wrong

### ISSUE THREAD

**Issue by kristian-b** [bueltge/MantisBT-Colorized#14]
Hi,

thank you for the great theme. I have spotted the following error:

![mantisbt-colorized-pw-forgotten](https://cloud.githubusercontent.com/assets/11410630/16820377/0340e612-4951-11e6-8f73-a494336fda04.PNG)

It would be great if you can fix that. Thank you.

Regards

**Comment by bueltge** [comment]
Which version of Mantis is that?

see my screenshot from Mantis 1.3.0-beta.2:
![auswahl_001](https://cloud.githubusercontent.com/assets/133425/16831793/25ed6b6c-49a7-11e6-89da-1c03eef37ce3.png)

**Comment by kristian-b** [comment]
Thank you for your reply. I am using version 1.3.0master-1.3.x-6e1766b

**Comment by bueltge** [comment]
Ok, I will update my bt and test again.

**Comment by bueltge** [comment]
Ok, should be fixed now. I have set a css rule only for the login screen, now also on this screen.

**Comment by kristian-b** [comment]
Great! Thank you.
