### ISSUE TITLE
Mantis 1.3.0 compatibility

### ISSUE THREAD

**Issue by marco-solare** [bueltge/MantisBT-Colorized#4]
Hi Frank, 
thanks for this great theme first of all!
It kinda brings mantis to 2015 in my opinion :)

I tried to use it with a 1.3.0b-2 installation of mantis.

I followed your setup instructions and it worked fine apart from the uri to the css. 
In the instructions you specified:

    $g_css_include_file = "/colorized/colorized.css";

However I had to put:

    $g_css_include_file = "../colorized/colorized.css";

to make it work.
Before that it did not seem to have any stylesheets attached anymore.

It worked then however it seems that the mantis team implemented some changes to the structure so it looks like so now:
https://twitter.com/MarcoSola/status/588698337047617536

and I guess that is not intended, at least for the styling of the menus on the top (uses up alot of space as they are displayed vertically not horizontally as intended)

I experimented a bit and after inspecting the DOM of the mantis document a bit I quickly realized that something like

    ul#menu-items li  {
    	float:left;
    	padding-right: 20px;
    	list-style-type: none;
    	background-color: #EEE;
    }

would at least bring back the horizontal orientation of what I would call the main menu.
It is the first time I look into mantis so I am not familiar with their DOM structure.

Now it would be great if you tweaked the theme to make it work for 1.3.x as it seems to be under active development and it was the best one I found researching.

Maybe create a 1.3.x branch in your git repo?

best,
Marco.

**Comment by bueltge** [comment]
Hi Marco.
Thanks for this hints. Currently I haven't work with Mantis 1.3.*
I have created the new branch for the 1.3 version of Mantis. Can you add new changes via Pull Request?

**Comment by bueltge** [comment]
ps. I have write to the Mantis Core team about the team to leave this in his repository, but I haven't an answer. I think it would be easier to find for mantis users to work and develop on the theme for Mantis.

**Comment by bueltge** [comment]
I found different hints for the 1.3

* https://github.com/mantisbt/mantisbt/wiki/Developer-changes-in-1.3.x

**Comment by marco-solare** [comment]
Hi Frank,
thanks for your reply!

well, for now I could send you all the things I find.
I'm not sure if I will have the time to send you pull requests, but I could open an issue or append to this issue if I find some more "incompatibilities". 
I think it basically is some minor changes in the (x)html structure (and therefore also the css) they implemented which cause some small potential problems on existing themes.
There is some more information about the structural changes over here on their blog.
However this is a rather old post, I'm usure about its relevance.
https://www.mantisbt.org/blog/?p=129

anyway, another pragmatic approach would be to simply look into their `default.css` file which seems to be the place where they define all the css styles (besides the jquery-ui.css they also seem to include).

Just search for the  `.main-menu ` declarations there (lines 137 to 143), analyse these couple of lines and take something similar - at least for attributes like `float position margin padding list-style` etc. and the main menu of your theme will be horizontal again :)

I looked into it up to this level but no further (sub menus etc) I guess if you want to provide a theme for 1.3.x you will have to look into their css a bit - after an hour or two you sure have an idea how to enhance / change your existing theme to make it work with the new version I guess

**Comment by marco-solare** [comment]
I could also test incoming changes on a 1.3.0 beta-2 (3...) I am currently running

**Comment by bueltge** [comment]
Hello Marco,

issues is also fine and helpful. Currently I found no time to validate the 1.3* and hints, comments, issue are welcome, also pull request, if you can.

**Comment by bueltge** [comment]
@marco-solare I have change a lot of rules and add also more rules to create the idea to MantisBT 1.3*. Maybe you check out this branch and test with this current status. Thanks for your feedback.

As hint. The Font "Open Sans" is now locally inside the theme, faster and easier to use in intranet, offline solutions.

**Comment by bueltge** [comment]
Thanks for the feedback!

**Comment by bueltge** [comment]
The mantisVersion 1.3.x Branch is now the default branch for developing. Also I release a stable version as tag - https://github.com/bueltge/MantisBT-Colorized/releases
