### ISSUE TITLE
the main buttion is missing from the top menu

### ISSUE THREAD

**Issue by mbassiouny33** [bueltge/MantisBT-Colorized#5]
hi,
At first I would like to thank you for this awesome theme, but when I tried to install it I ran into a small problem:
I have activated the news option in mantis by adding 
$g_news_enabled = ON;

i I tried it with the default theme and it worked just fine.
however when  I installed the colorized theme, the main page became >"my views" and the "main" is no longer accessible from the top menu.
Any help ? and thanks in advance
![main is missing on my site](https://cloud.githubusercontent.com/assets/12175103/7403847/926da6e0-eeda-11e4-9aa9-d669623939cd.PNG)
![main is not missing on my site](https://cloud.githubusercontent.com/assets/12175103/7403848/92700d04-eeda-11e4-84e6-e16b303c8709.PNG)

**Comment by bueltge** [comment]
Is you MantisBT public, can I see this online?

**Comment by mbassiouny33** [comment]
yup it's public, anyone can see it but registration is closed. can you give me your email so I can send you my account's password?

**Comment by bueltge** [comment]
fine. frank AT bueltge DOT de

**Comment by mbassiouny33** [comment]
sent :)

**Comment by bueltge** [comment]
Currently is the menu point hide via css, line 29

Uncomment this line and it should work.
`a[href*='/main_page.php'] { display: none !important; }`

**Comment by mbassiouny33** [comment]
Everything works fine now, Mr. bueltge helped me to get this done, thanks to him 

the solution as he just said is changing
a[href*='/main_page.php'] { display: none !important; }
 to
a[href='/main_page.php'] { display: none !important; }

the default page will be  the view issues page, If you want to make the default page the "main" news page; You can add this to the confic_inc.php
$g_default_home_page = 'main_page.php';
