### ISSUE TITLE
MantisThemeManager support.

### ISSUE THREAD

**Issue by kierun** [bueltge/MantisBT-Colorized#6]
https://github.com/TimPietrusky/MantisThemeManager

Currently, I cannot get it to work with the above.  Any ideas?

**Comment by kierun** [comment]
AH! Silly me: `ln -si colorized.css default.css` and all works!

**Comment by bueltge** [comment]
I have no experience with the theme manager, nice that you find the problem to solve the issue.

**Comment by kierun** [comment]
We've decided to use your great theme.  It really makes Mantis a lot easier to sell. The default "theme" is rather ugly.

Do you want me to fork, write some documentation, and submit a pull request or is this way too much work for three lines to text?

**Comment by bueltge** [comment]
Yes, please send me your additional commits, documentation and also changes, if is necessary.
Please see, that I have two branches, for the next version 1.3x of Mantis and the current stable version 1.2x.

Thanks a lot for your help!

**Comment by kierun** [comment]
I created a pull request.
