### ISSUE TITLE
Integrate into https://github.com/mantisbt-plugins

### ISSUE THREAD

**Issue by roman-1983** [bueltge/MantisBT-Colorized#8]
Would be great if you add your theme to the mantisbt-plugin repository.

**Comment by bueltge** [comment]
Yes. I will. I had write a lot of mails, but no answer from the team.

**Comment by atrol** [comment]
> but no answer from the team.

Seems we missed something.
Did you follow those steps?
https://www.mantisbt.org/wiki/doku.php/mantisbt:mantis_plugins#the_github_mantisbt-plugins_organization

**Comment by bueltge** [comment]
Not sure, long time ago. I have another plugin in the github-team, but this theme. My mails, two tryings, was without an answer. But I will do this again in this email-list.

**Comment by bueltge** [comment]
Ok now, the mail is done with the process from your link. Thx.

**Comment by bueltge** [comment]
Now, I get an answer:

>You are not allowed to post to this mailing list, and your message has been automatically rejected.  If you think that your messages are being rejected in error, contact the mailing list owner at mantisbt-dev-owner@lists.sourceforge.net.

I write again, after subscription the list.

**Comment by atrol** [comment]
No idea what's happening with the mailing list.

I created a team "Plugin Colorized" and added you as a member.
You can transfer now your repository.

**Comment by bueltge** [comment]
Thanks a lot, I will do that on the next view days.

**Comment by bueltge** [comment]
OK, now we have the theme include the MantisBT github repo - https://github.com/mantisbt-plugins/MantisBT-Colorized
