### ISSUE TITLE
<code> CSS (as "block")

### ISSUE THREAD

**Issue by sebald** [bueltge/MantisBT-Colorized#9]
`colorized.css` set the `<code>` alement as `display: block` (last line [on current master](https://github.com/bueltge/MantisBT-Colorized/blob/master/colorized.css#L199))

Is this line required for colorized? Because it messes up other plugins, e.g. [Markdown](https://github.com/bueltge/Markdown-for-MantisBT) :-/

**Comment by bueltge** [comment]
Yes, is necessary for me. If I format a code block inside the textareas then it is a block. I think, the follow screenshots demonstrate it better.

### Without display block
![without-block](https://cloud.githubusercontent.com/assets/133425/13433465/4b37712c-dfd2-11e5-92e6-c6d95b15e787.png)

### With display block
![with-block](https://cloud.githubusercontent.com/assets/133425/13433474/54070f38-dfd2-11e5-967e-9842b7d57701.png)

**Comment by sebald** [comment]
But isn't that the difference between `<pre><code>` blocks and `<code>` blocks in HTML?
Or in GFM 
- *```* for blocks
- *`* for inline code

If there is only block level styling, you remove the option to write inline code.

**Comment by bueltge** [comment]
Yes, you have right. 
We should switch from `code { display: block; }` to `pre code { display: block; }`.

**Comment by bueltge** [comment]
@sebald I have change this in all branches, maybe you will test.
Thanks!

**Comment by sebald** [comment]
Of course. Will do!

I'll get to you in a view days :)

**Comment by bueltge** [comment]
:+1:

**Comment by sebald** [comment]
We tested it and everything works fine now! :)

**Comment by bueltge** [comment]
:100: :bouquet: 
Thanks for your feedback.

**Comment by sebald** [comment]
Thanks for writing and **maintaining** "old" Mantis Plugins!!! :)

**Comment by bueltge** [comment]
How do you mean old? The plugin is not really old, but Mantis is it ;)

**Comment by sebald** [comment]
That's true :) I guess everything related to Mantis seems old to me :D

**Comment by bueltge** [comment]
Yes, that's also true.
